* direct-svg

=direct-svg= is a javascript library that allows for easy, yet explicit
creation of svg graphics. Dom objects are created and returned
directly, such that vanilla javscript can be used for transforming and
building dom trees.

** object creation

Given an html-document with a container element, e.g. =<div
id='content'></div>=, the following javascript snippert would create
a svg element containing a black circle with radius 5 px at position
(10 px, 10 px).
#+BEGIN_SRC javascript
var content = document.getElementById('content');

var svg = SVG.svg(20, 20);
content.appendChild(svg);

var circle = SVG.circle(10, 10, 5, {'fill': 'black'});
svg.appendChild(circle);
#+END_SRC

The basic method for creating dom elements is =create(name, attrs)=,
where =name= is the element descriptor, e.g. ='circle'=, and =attrs= is an
object, containing all parameters that can be set by
=domElement.setAttribute=. So the above example, internally calls

#+BEGIN_SRC javascript
var content = document.getElementById('content');

var svg = SVG.svg(20, 20);
content.appendChild(svg);

var circle = SVG.create({'cx': 10, 'cy': 10, 'r': 5, 'fill': 'black'});
svg.appendChild(circle);
#+END_SRC

Some more convenience functions exist, e.g. line, point, rectangle,
group.

** object manipulation
